return {}
-- return {
-- 	{
-- 		"Exafunction/codeium.nvim",
-- 		dependencies = {
-- 			"nvim-lua/plenary.nvim",
-- 			"hrsh7th/nvim-cmp",
-- 		},
-- 		config = function()
-- 			require("codeium").setup({
-- 				enable_chat = true,
-- 				-- config_path = "./key.json",
-- 				-- config_path = "D://Private Data//Programs/New Self Learning JS Projects//React-Projects//",
-- 				-- config_path = "C://Users/abhis/key.json",
-- 				-- config_path = "C://Users/abhis/key.gzip",
-- 			})
-- 		end,
-- 	},
-- }
